apiVersion: v2
description: Boilerplate templates
icon: https://raw.githubusercontent.com/self-hosters-by-night/helm-charts/refs/heads/main/assets/boilerplate.png
name: boilerplate
type: library
version: 0.16.0
