apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Release.Name }}-ldap
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    sectionName: "{{ .Release.Name }}-ldap"
  rules:
  - backendRefs:
    - name: {{ .Release.Name }}
      port: 3890
